#!/usr/bin/env bash
# Regenerate openspec/changes/archive/INDEX.md from the filesystem.
#
# Idempotent: re-running with no archive changes produces byte-identical output
# and exits 0 with no writes (diff-compare before writing).
#
# Spec: openspec/changes/add-doc-lifecycle-infra/specs/docs-lifecycle/spec.md
#       Requirement "Archive index is generated, not hand-maintained".

set -euo pipefail
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)"
ROOT="$(pwd)"
ARCHIVE_DIR="$ROOT/openspec/changes/archive"
INDEX="$ARCHIVE_DIR/INDEX.md"

[ -d "$ARCHIVE_DIR" ] || { echo "no archive dir at $ARCHIVE_DIR" >&2; exit 0; }

# Extract a one-line summary from the first paragraph under `## Why` in proposal.md.
summarize() {
  local proposal="$1"
  local change_id="$2"
  if [ ! -f "$proposal" ]; then
    printf '%s' "$change_id"
    return
  fi
  awk '
    /^## Why/ { in_why=1; next }
    in_why && /^## / { exit }
    in_why && NF && !/^#/ {
      # Collapse pipes and trim
      gsub(/\|/, "\\|")
      gsub(/  +/, " ")
      sub(/^ +/, "")
      sub(/ +$/, "")
      print
      exit
    }
  ' "$proposal"
}

extract_date() {
  # directory name pattern YYYY-MM-DD-...
  printf '%s' "${1:0:10}"
}

extract_id() {
  printf '%s' "${1:11}"
}

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# Archive Index"
  echo ""
  echo "> Generated by \`.claude/scripts/gen-archive-index.sh\`. Do not hand-edit."
  echo ""
  echo "| Date       | Change ID                             | Summary                                               |"
  echo "|------------|---------------------------------------|-------------------------------------------------------|"

  find "$ARCHIVE_DIR" -mindepth 1 -maxdepth 1 -type d -print \
    | sort -r \
    | while read -r d; do
        base="$(basename "$d")"
        date="$(extract_date "$base")"
        id="$(extract_id "$base")"
        summary="$(summarize "$d/proposal.md" "$id")"
        [ -n "$summary" ] || summary="(no proposal.md)"
        # truncate long summaries for table readability (character-safe, not byte-safe)
        if [ "${#summary}" -gt 60 ]; then
          summary="${summary:0:57}..."
        fi
        printf '| %-10s | %-37s | %-53s |\n' "$date" "$id" "$summary"
      done
} > "$TMP"

# Idempotent diff-only write
if [ -f "$INDEX" ] && cmp -s "$TMP" "$INDEX"; then
  exit 0
fi

mv "$TMP" "$INDEX"
echo "wrote $INDEX"
